PixarAnimationStudios/USD

- pxr/usd/plugin/usdAbc/wrapAlembicTest.cpp
Reorder includes, as in other wrap*cpp files, to work around build breakage due to Python bug on OSX in < 2.7.13 , as described in issue #28 .
> Fix OSX build by reordering includes as described in issue #28

- README.md
OpenEXR link was broken; updated to current webpage.
> Fix link to OpenEXR webpage.

- pxr/base/lib/tf/CMakeLists.txt
Fixes issue #66 by adding wrapTestPyAnnotatedBoolResult to build.
> [Tf] Add wrapTestPyAnnotatedBoolResult to build, fixing linking errors.

- extras/usd/examples/usdObj/CMakeLists.txt
- extras/usd/examples/usdObj/plugInfo.json
…PXR_PLUGINPATH_NAME bootstrapping. Otherwise the user must manually edit the usdObj plugInfo.json , etc., in order for Plug to find what it needs.
> usdObj: Clean up build and plugInfo for proper installation into examples.

- cmake/modules/FindPySide.cmake
Add support for 'python2-pyside-uic' as a searched executable
name for pyside. This is the executable name used on Arch Linux.
> Alternative executable name for uic

- pxr/usd/lib/usdShade/parameter.h
> Fix symbol visibility for UsdShadeParameter::GetConnectionRelName.

- pxr/base/lib/tf/testenv/SIGSEGV.cpp
> Include missing nap.h for SIGSEGV test in dev_win_ip.

- pxr/usd/plugin/usdAbc/alembicWriter.cpp
Const-correct use of OArchive for alembicWriter, required by Alembic 1.7 compilation, and verified backwards compatible with earlier Alembic as well.
Fixes issue #106 .
> [usdAbc] Fix build for Alembic 1.7 .

- pxr/imaging/lib/hd/engine.cpp
Fixes a typo that compares rather than assigns.
> [Hd] Fix assignment typo as equivalence.

- third_party/maya/lib/usdMaya/usdExport.cpp
- third_party/maya/lib/usdMaya/usdImport.cpp
The usdImport / usdExport modules contain a lot of sections like this:
```cpp
if (argData.isFlagSet("mergeTransformAndShape")) {
bool tmpBool = true;
argData.getFlagArgument("mergeTransformAndShape", 0, tmpBool);
jobArgs.mergeTransformAndShape = tmpBool;
}
```
As far as I can tell, there is no need for the "tmpBool" variables, so I've made a small code-cleanup pull request which changes these sections to:
```cpp
if (argData.isFlagSet("mergeTransformAndShape")) {
argData.getFlagArgument("mergeTransformAndShape", 0, jobArgs.mergeTransformAndShape);
}
```
- 3a55dc24c5f6a1b10087a430627f88f9a2d8a3b1
- none
> get rid of unnecessary tmpBool vars

- cmake/defaults/gccclangshareddefaults.cmake
- pxr/base/lib/arch/attributes.h
- pxr/base/lib/arch/nap.cpp
- pxr/base/lib/tf/testenv/SIGFPE.cpp
Use constructor/destructor attributes to add to ELF's .init .fini sections.
Enable pause instruction on Intel CPU built with clang.
Only add -Wno-unused-local-typedefs if clang version is > 3.5.
ARCH_CONSTRUCTOR/ARCH_DESTRUCTOR not being called when built with clang on Linux.
ArchThreadPause doing nothing built with clang.
Tons of warning related to -Wno-unused-local-typedefs not being understood.
> Fixes for building with clang.

- pxr/usdImaging/lib/usdviewq/__init__.py
Replaced Windows style slashes with forward slashes so that the path can be digested correctly in the Qt style sheet.
Also removed redundant slash at the end of `resourceDir` variable, since this separator is added in usdviewstyle.qss
> Windows: Fixed path separators for usdview stylesheet 

- third_party/katana/lib/katanaAttrfncApi/CMakeLists.txt
- third_party/katana/lib/katanaOpApi/CMakeLists.txt
- third_party/katana/plugin/pxrUsdInShipped/CMakeLists.txt
Fixing Katana plugin linking issues.
- pointInstancer.cpp not included in pxrUsdInShipped.
- typos in katanaAttrfncApi and katanaOpApi CMakeLists.txt, the client subfolder doesn't exists for FnPluginSystem as of Katana 2.5v5.
> Fixing katana plugin linking issues.

- cmake/macros/Public.cmake
Fix issue #84 by generating files and installing them in separate steps.
> build: fix cmake DESTDIR support

- pxr/usd/plugin/usdAbc/wrapAlembicTest.cpp
See issue #28 and https://bugs.python.org/issue10910  for more details. Workaround is to violate coding conventions with this include order.
> [usdAbc] Fix build for pyport include workaround (issue #178).

- third_party/maya/lib/usdMaya/CMakeLists.txt
- third_party/maya/lib/usdMaya/shadingModeDisplayColor.cpp
- third_party/maya/lib/usdMaya/shadingModeExporter.cpp
- third_party/maya/lib/usdMaya/shadingModeExporter.h
- third_party/maya/lib/usdMaya/shadingModeExporterContext.cpp
- third_party/maya/lib/usdMaya/shadingModeExporterContext.h
- third_party/maya/lib/usdMaya/shadingModePxrRis.cpp
- third_party/maya/lib/usdMaya/shadingModeRegistry.cpp
- third_party/maya/lib/usdMaya/shadingModeRegistry.h
- third_party/maya/lib/usdMaya/translatorMaterial.cpp
This change deals with redesigning the shading mode export/import interface. As a first step, it's a take on the export interface. I tried to create a bit more flexible export process, so exporters can overwrite the whole process too if they don't want to go through the exporter context.
This is just a take on the shading mode export, so feedback can be gathered, before moving on to the importers.
- There is no way to do stateful shading mode export / import interfaces.
- There is no way to include spaces in the shading mode exporter's/importer's name, so lots of manual remapping is required.
- No easy way to link the same exporter to multiple modes.
- Exporters can't take over the whole process themselves, just by one shading node at a time.
> Redesigning the shading mode export interface

- third_party/maya/lib/usdMaya/translatorModelAssembly.cpp
Small fix for assembly creation - python command was missing import
- f10b832e25e17c6b849d5594da2fdab8f2ca358f
- Would fail creating assemblies if used in a fresh / stock maya, with no userSetup.py, etc.
> missing python import

- third_party/maya/lib/usdMaya/CMakeLists.txt
- third_party/maya/lib/usdMaya/shadingModeRegistry.cpp
- third_party/maya/lib/usdMaya/shadingModeRegistry.h
- third_party/maya/lib/usdMaya/usdListShadingModes.cpp
- third_party/maya/lib/usdMaya/usdListShadingModes.h
- third_party/maya/lib/usdMaya/usdTranslatorExport.cpp
- third_party/maya/lib/usdMaya/usdTranslatorExport.mel
- third_party/maya/lib/usdMaya/usdTranslatorImport.cpp
- third_party/maya/lib/usdMaya/usdTranslatorImport.mel
- third_party/maya/plugin/pxrUsd/plugin.cpp
The change builds the Shading Mode list dynamically, instead of hard coding the values in the Mel scripts. The advantage of this change is adding a new shading mode export won't require manual changes in the UI scripts, and the translatorMaterial will use the right exporter at export time.
To make this work, I needed to add a new command to list the export/import Shading Modes, similar functions to the Registry, and modify the UI scripts to build the optionMenu based on the output of the command.
N/A
> Setting up the shading mode option menu dynamically.

- third_party/maya/plugin/pxrUsd/plugin.cpp
Was a typo in deregistering usdListShadingModes 
- https://github.com/PixarAnimationStudios/USD/commit/fac7b79b3e30c5d381e2e176388a13d318f31ed4
- None reported - likely an error on unloading plugin
> Fix for deregistering usdListShadingModes command

- third_party/maya/lib/usdMaya/CMakeLists.txt
- third_party/maya/plugin/pxrUsd/CMakeLists.txt
...as this is the only cmake-variable guaranteed to be set after FindMaya runs
Makes the CMakeLists.txt use $MAYA_BASE_DIR, since $MAYA_LOCATION may not be defined.
- https://github.com/PixarAnimationStudios/USD/commit/11ed4f3ebb9283c2fdd555c6c26e3185fc888915
- Allows tests to work properly in situations where cmake was not called with an explicit "-D MAYA_LOCATION=/path/to/maya", but instead relies on setting $MAYA_LOCATION as shell environment variable (where it is then converted to the MAYA_BASE_DIR cmake-variable)
> [usdMaya] [tests] cmake should use $MAYA_BASE_DIR not $MAYA_LOCATION

- third_party/maya/lib/usdMaya/JobArgs.cpp
...this brings it in line with the gui, where it was already changed to true by default
This was made after discussion here (https://github.com/PixarAnimationStudios/USD/pull/164), where it was decided to just make it true by default everywhere (and not have it controlled by an env var option).
- https://github.com/LumaPictures/USD/commit/cf7b562c2dacb1a38c85ae08247f51d6ea688a33
- https://github.com/PixarAnimationStudios/USD/issues/145
> readAnimData is on by default for commands

- pxr/base/lib/arch/debugger.cpp
- pxr/base/lib/arch/env.cpp
- pxr/base/lib/arch/env.h
- pxr/base/lib/arch/stackTrace.cpp
Trying to link to **environ** variable fails when OS X SDK < 10.11
> Add inlined ArchEnviron function for OS X.

- third_party/katana/plugin/pxrUsdInShipped/CMakeLists.txt
LightOp symbols are missing from the katana plugin build.
> [usdKatana] Fixing missing symbol from the Katana plugin.

- third_party/maya/lib/usdMaya/referenceAssembly.cpp
- third_party/maya/lib/usdMaya/referenceAssembly.h
- third_party/maya/lib/usdMaya/translatorModelAssembly.cpp
The same string constant - the prefix before attribute names used to select variant sets - was defined in two different places: as `USD_VARIANT_SET_PREFIX` in `referenceAssembly`, and `_tokens->VariantSetPlugNamePrefix` in `translatorModelAssembly`.  It caused some initial confusion, so I decided to unify on `PxrUsdMayaVariantSetTokens` in `referenceAssembly`. (I placed it in `referenceAssembly`, because `translatorModelAssembly` already includes `referenceAssembly`, but not vice-versa.)
- https://github.com/PixarAnimationStudios/USD/commit/0feb6e267be64d3103ac58eda39b45d408cf5c28
- None filed
> create single token for "usdVariantSet_"

- cmake/macros/testWrapper.py
Currently running the tests will error in testWrapper.py if you have an environ var (in our case, it was PYTHONPATH) that has an '=' in it. This fixes it deal properly with such vars.
- https://github.com/PixarAnimationStudios/USD/commit/6f9a52afdcdb09dffbc72a0e872591deec3dfd7a
- running tests when an env var has a '='
> [tests] deal with env vars that have an '=' in them

- third_party/maya/lib/usdMaya/CMakeLists.txt
- third_party/maya/lib/usdMaya/FunctorPrimWriter.cpp
- third_party/maya/lib/usdMaya/FunctorPrimWriter.h
- third_party/maya/lib/usdMaya/JobArgs.cpp
- third_party/maya/lib/usdMaya/JobArgs.h
- third_party/maya/lib/usdMaya/MayaCameraWriter.cpp
- third_party/maya/lib/usdMaya/MayaCameraWriter.h
- third_party/maya/lib/usdMaya/MayaMeshWriter.cpp
- third_party/maya/lib/usdMaya/MayaMeshWriter.h
- third_party/maya/lib/usdMaya/MayaNurbsCurveWriter.cpp
- third_party/maya/lib/usdMaya/MayaNurbsCurveWriter.h
- third_party/maya/lib/usdMaya/MayaNurbsSurfaceWriter.cpp
- third_party/maya/lib/usdMaya/MayaNurbsSurfaceWriter.h
- third_party/maya/lib/usdMaya/MayaPrimWriter.cpp
- third_party/maya/lib/usdMaya/MayaPrimWriter.h
- third_party/maya/lib/usdMaya/MayaTransformWriter.cpp
- third_party/maya/lib/usdMaya/MayaTransformWriter.h
- third_party/maya/lib/usdMaya/primWriterRegistry.h
- third_party/maya/lib/usdMaya/usdExport.cpp
- third_party/maya/lib/usdMaya/usdTranslatorExport.cpp
- third_party/maya/lib/usdMaya/usdTranslatorExport.h
- third_party/maya/lib/usdMaya/usdTranslatorExport.mel
- third_party/maya/lib/usdMaya/usdWriteJob.cpp
- third_party/maya/lib/usdMaya/usdWriteJob.h
- third_party/maya/lib/usdMaya/usdWriteJobCtx.cpp
- third_party/maya/lib/usdMaya/usdWriteJobCtx.h
- third_party/maya/lib/usdMaya/util.h
This PR focuses on export instances from Maya. Right now import is not yet supported since this is a significant change, I want to gather some feedback before implementing the import side of the modification.
A couple of notes.
- I renamed "Make Instances" to "Make References Instanceable" to avoid confusion and make the difference between instances and that flag.
- The central part of the change is creating a new class, usdWriteJobCtx, which is the parent of usdWriteJob. This ctx is meant to be passed to the writers and has common functionality that's useful both in usdWriteJob and each of the writers. The writer creation is also moved here, because in our approach to instances, ever shape is an instance and the instances created in a different scope. The ctx handles this creation …
> [usdMaya] Exporting instances from Maya.

- pxr/usdImaging/lib/usdviewq/__init__.py
- pxr/usdImaging/lib/usdviewq/mainWindow.py
Allows choosing of what camera to use when opening the scene
- https://github.com/PixarAnimationStudios/USD/commit/f2f5e997be58d64f76a754ba703c7e0203bc0cc3
- None, perse, but there was a TODO note about not hardcoding the default to be a pixar-specific name, which this effectively does
> [usdview] add --camera cmdline arg

- cmake/macros/Private.cmake
- pxr/CMakeLists.txt
Since v0.7.6 usd cmake's targets are not exported anymore. Was this intended? We're relying on this at the moment.
Cheers.
-
> Export and install pxrTargets.cmake.

- pxr/imaging/lib/hd/changeTracker.cpp
- pxr/imaging/lib/hd/changeTracker.h
- pxr/imaging/lib/hdSt/renderPass.cpp
This makes a few more methods `const` so that a reference to
the change tracker in the render pass code can also be `const`.
> HdChangeTracker const correctness improvements.

- pxr/imaging/lib/hdSt/instancer.h
- pxr/usd/lib/usd/prim.h
Clang issues a warning when forward declarations don't match the
actual declaration about whether something is a struct or class.
> Fix mismatched tags warnings under clang.

- pxr/imaging/lib/hdSt/basisCurvesComputations.h
- pxr/imaging/lib/hdSt/renderDelegate.h
- pxr/imaging/lib/hdSt/subdivision3.cpp
- pxr/usd/lib/sdf/layerStateDelegate.h
When some declarations in a class use 'override' but not all virtual
methods do, clang issues a warning.
> Fix warnings about missing 'override'.

- pxr/usd/lib/sdf/textFileFormat.tab.cpp
- pxr/usd/lib/sdf/textFileFormat.yy
This fixes a warning about an unused private field on the class.
> Remove unused private field: _fileBufferSize.

- pxr/usdImaging/lib/usdviewq/layerStackContextMenu.py
- pxr/usdImaging/lib/usdviewq/mainWindow.py
useful when using Assest Resolvers, where the "real path" may be less useful than the unresolved identifier
Adds in a new right-click menu item that will copy the layer identifier (ie, unresolved asset path) to the clipboard
- None
> usdview: add "Copy Layer identifier" menu item

- third_party/maya/lib/usdMaya/registryHelper.cpp
- third_party/maya/lib/usdMaya/registryHelper.h
- third_party/maya/lib/usdMaya/shadingModeRegistry.cpp
- third_party/maya/lib/usdMaya/usdExport.cpp
- third_party/maya/lib/usdMaya/usdListShadingModes.cpp
- third_party/maya/lib/usdMaya/usdTranslatorExport.cpp
This PR is a general improvement for the shading mode exporter plugin interface.
- Previously there was no functionality to load the plugins. I added a function similar to the primWriter plugin loading code, that's run before any of the exporters are accessed.
- The default values caused a bit of confusion. The GPrim Colors -> displayColor remapping was missing from the export code (both the translator and the usdExport call).
- A request to an invalid export appended empty exporter to the list with the same name. This problem was fixed by accessing the exporter through an iterator rather than std::map's operator[].
- If the manual export command was used instead of the file translator, the shading mode worked incorrectly. The shading modes were accessible by their internal names, which …
> [usdMaya] Loading the shading mode plugins.

- third_party/maya/lib/pxrUsdMayaGL/proxyDrawOverride.cpp
- third_party/maya/lib/pxrUsdMayaGL/proxyDrawOverride.h
This PR enables Maya VP2 rendering of proxy shapes.
Proxy shapes were not visible in VP2 because of the missing supportedDrawAPIs.
> Enabling proxy draw overrides for VP2.

- third_party/katana/lib/usdKatana/utils.cpp
Supporting 4 component vector and 4 component vector array primvars in pxrUsdIn. Without this, there are a bunch of errors thrown, and with this, we can support RGBA color sets exported from Maya.
> [Katana] Support vec4 primvars.

- third_party/maya/lib/usdMaya/shadingModeExporter.cpp
- third_party/maya/lib/usdMaya/shadingModeExporter.h
- third_party/maya/lib/usdMaya/translatorMaterial.cpp
- third_party/maya/lib/usdMaya/translatorMaterial.h
- third_party/maya/lib/usdMaya/usdWriteJob.cpp
The following change passes the Maya DagPath to Usd Prim Path map to the shader exporters. This is useful when implementing the material export the other way around, looking up the materials of the existing nodes, rather than iterating through all the existing shading engines in the scene.
We are relying on this in our usd-arnold package.
> [usdMaya] Passing dagPathToUsdPathMap to the material translator.

- third_party/maya/lib/usdMaya/CMakeLists.txt
- third_party/maya/lib/usdMaya/module.cpp
- third_party/maya/lib/usdMaya/testenv/UsdImportXformsTest/UsdImportXformsTestRotateAxis.usda
- third_party/maya/lib/usdMaya/testenv/testUsdImportXforms.py
- third_party/maya/lib/usdMaya/testenv/testUsdMayaXformStack.py
- third_party/maya/lib/usdMaya/translatorXformable.cpp
- third_party/maya/lib/usdMaya/wrapXformStack.cpp
- third_party/maya/lib/usdMaya/xformStack.cpp
- third_party/maya/lib/usdMaya/xformStack.h
This factors out the code for defining standardized transform stacks into a new class, xformStack.  This class is also responsible for checking compatibility with existing usd xform stacks.  This code is also exposed through the API for use externally.
There's actually nothing in the code which is specific to maya, so in theory it could be promoted to somewhere in the usd core, but it may be premature if it's not used anywhere else yet... and, of course, I'm sure that would warrant a higher level of scrutiny.
Speaking of scrutiny - I'm planning to add some unit tests, but wanted to give a chance for comment now!
> [maya] factor out matching of xforms into PxrUsdMayaXformStack

- third_party/houdini/lib/gusd/GU_USD.cpp
- third_party/houdini/lib/gusd/PRM_Shared.cpp
- third_party/houdini/lib/gusd/refiner.cpp
This misuse of PRM_AutoDeleter was caught by running through an address sanitizer which pointer out the use of malloc to allocate and delete to free the stolen string.
The GA_Offset casting is from a build of Houdini where GA_Offset is a class, not a simple typedef to int. Often this catches bad code. The code in GU_Usd.cpp actually looks a bit suspicious, but I can't find any evidence it is actually called, so perhaps this function should be deleted?
> Auto deleter for pointers stolen from a UT_String needs to be a callback deleter

- third_party/houdini/lib/gusd/GT_PackedUSD.cpp
- third_party/houdini/lib/gusd/GT_PackedUSD.h
- third_party/houdini/lib/gusd/GT_PrimCache.h
- third_party/houdini/lib/gusd/UT_CappedCache.h
- third_party/houdini/lib/gusd/UT_StaticInit.h
- third_party/houdini/lib/gusd/UT_Version.h
- third_party/houdini/lib/gusd/primWrapper.cpp
- third_party/houdini/lib/gusd/shaderWrapper.cpp
- third_party/houdini/lib/gusd/stageCache.cpp
- third_party/houdini/lib/gusd/stageCache.h
- third_party/houdini/plugin/OP_gusd/OBJ_usdcamera.h
- third_party/houdini/plugin/OP_gusd/ROP_usdoutput.h
Some typos in include guards.
Adding override keyword consistently on virtual overrides.
Placing assignments in if() expressions inside parentheses.
Removing unuse m_purposeSet member data.
Pre-declare a class as a class, not as a struct.
These warnings were all reported by clang.
> Fix a number of minor warnings in the Houdini plugin code.

- pxr/usd/lib/pcp/node.h
Change the visibility of pcp child nodes iterator.
We came across this while building [AL_USDMaya](https://github.com/AnimalLogic/AL_USDMaya/blob/develop/lib/AL_USDMaya/AL/usdmaya/cmds/LayerCommands.cpp#L731) on Windows where symbols are hidden by default.
The same symbols from the reverse iterator should also probably be exposed.
- Unable to build and use the iterator on Windows
> [Usd] Change visibility of pcp child nodes iterator.

- third_party/maya/lib/usdMaya/usdReadJob.cpp
Currently, when the maya plugin is passed an invalid primPath (either one that has bad syntax, like "bad;primPath", or one that doesn't exist in the scene, like "/prim/doesnt/exist"), the plugin silently just converts this to a pseudoRoot ("/").  I feel that it should, at minimum, print a warning - so I've made a commit / pull request that does that.
It think it would be still more preferable to have it "abort" and return false, similar to the behavior if the stage has an invalid defaultPrim (the handling of which is a few lines below).  However, I was hesitant to change existing behavior without sanction.  If returning false would be preferable, though, it's an easy addition.
- https://github.com/PixarAnimationStudios/USD/commit/efaec0a98654e8d2eb001b0668f95fbff86aaa60
- None reported, …
> usdMaya: warn if falling back to pseudoRoot due to failed primPath

- pxr/base/lib/tf/pathUtils.cpp
This fixes a warning when building on macOS.
> _ExpandSymlinks is only used on Windows, so only build it there.

- pxr/base/lib/arch/mallocHook.cpp
This code is only used on Linux, so only build it there.
> Remove unused malloc hook functions on non-Linux platforms.

- third_party/maya/lib/usdMaya/translatorGprim.cpp
If a mesh is "doubleSided", do not export an "opposite" attribute. The "opposite" attribute is disabled and disregarded in maya, so it should not be set in usd. (Before "opposite" was getting exported regardless of "doubleSided".)
This is a fix for getting different sidedness across DCCs.
When a mesh is doubleSided, maya ignores the "opposite" sidedness, and treats the mesh the same as if it were unchecked. However, once you've exported the mesh to USD it would pick up on the disabled checkboxes state and will give you a different result. Other DCC's that consume the USD file will then have a different picture of the mesh than existed in maya.
> [maya] fix for exporting orientation attribute for doubleSided meshes

- third_party/maya/lib/usdMaya/shadingModeExporter.cpp
- third_party/maya/lib/usdMaya/shadingModeExporter.h
- third_party/maya/lib/usdMaya/shadingModeExporterContext.cpp
- third_party/maya/lib/usdMaya/shadingModeExporterContext.h
This adds two new virtual methods, PreExport and PostExport, which provide points at which sub-classes can customize the shader export process.
- A recent commit made DoExport no longer a virtual method; while this ensured a more unified export process, it also meant a loss of flexibility for shader exporters which need to do some sort of setup + tear down. This commit restores the ability for third-party subclasses to do such things.
> [usdMaya] add PreExport / PostExport to PxrUsdMayaShadingModeExporter

- pxr/base/lib/gf/matrix.template.cpp
- pxr/base/lib/gf/matrix.template.h
- pxr/base/lib/gf/matrix2d.cpp
- pxr/base/lib/gf/matrix2d.h
- pxr/base/lib/gf/matrix2f.cpp
- pxr/base/lib/gf/matrix2f.h
- pxr/base/lib/gf/matrix3d.cpp
- pxr/base/lib/gf/matrix3d.h
- pxr/base/lib/gf/matrix3f.cpp
- pxr/base/lib/gf/matrix3f.h
- pxr/base/lib/gf/matrix4d.cpp
- pxr/base/lib/gf/matrix4d.h
- pxr/base/lib/gf/matrix4f.cpp
- pxr/base/lib/gf/matrix4f.h
Pretty self explanatory. I wanted to use GfMatrid4d.Get from a const instance, but couldn't.
- None reported
> mark the GfMatrix*.Get method const

- third_party/maya/lib/usdMaya/CMakeLists.txt
- third_party/maya/lib/usdMaya/UsdGeomAttributeConverters.cpp
- third_party/maya/lib/usdMaya/testenv/UsdGeomAttributeConvertersTest/UsdAttrs.usda
- third_party/maya/lib/usdMaya/testenv/testUsdGeomAttributeConverters.py
The change adds an attribute converter for the purpose attribute on UsdGeomImageable. This makes setting up proxies for usdview / katana way simpler, and users don't have to implement it for themselves.
> [usdMaya] Adding an attribute converter for UsdGeom purpose.

- pxr/usd/bin/usdcat/usdcat.py
- pxr/usd/bin/usdcheck/usdcheck.py
- pxr/usd/bin/usddiff/usddiff.py
- third_party/katana/lib/usdKatana/cache.cpp
- third_party/maya/lib/usdMaya/usdImport.cpp
Fixes to allow usage of unresolved asset paths with both the command-line tools and the katana plugin
- ~~https://github.com/LumaPictures/USD/commit/f903a6e130787e38808ea014a7bd1b9f7c2c9551~~
- ~~https://github.com/LumaPictures/USD/commit/c575ac5035c7f005da67d357dac84ee7b2baf6b6~~
- ~~https://github.com/LumaPictures/USD/commit/55502b743275390d9ef4f3ed0b623324c6123f13~~
- ~~https://github.com/PixarAnimationStudios/USD/pull/165/commits/562ec2cf0abd854e4919247c479ce1bb46322b3a~~
- ~~https://github.com/PixarAnimationStudios/USD/pull/165/commits/2a63b3628aab2e7011b56658f43b57c4f4a277c2~~
- ~~https://github.com/PixarAnimationStudios/USD/pull/165/commits/d4a74d56b94f0c9aae0ff48820368903c59de470~~
- ~~https://github.com/PixarAnimationStudios/USD/pull/165/commits/eb955914b8bcf72670fd22b1e135def3e2c …
> Cmdline ar resolver

- third_party/maya/lib/usdMaya/MayaPrimWriter.cpp
- third_party/maya/lib/usdMaya/MayaPrimWriter.h
- third_party/maya/lib/usdMaya/usdWriteJob.cpp
The change is super simple here; we are clearing the prim writers before saving the stage. This change is useful when somebody wants to run cleanup code in a primWriter's destruction. Otherwise, there is no way to track down the last write to get the same effect.
For example, we have been using feature successfully with some of our writers to optimize animation data before saving the stage.
> [usdMaya] Clearing out the prim writers before saving the stage.

- third_party/katana/lib/usdKatana/readPointInstancer.cpp
- third_party/katana/lib/usdKatana/utils.cpp
- third_party/katana/lib/usdKatana/utils.h
The following changes cases when infinite recursion happens in pxrUsdIn when sources are outside the scope of the pointInstancer. The change also deals with corner-case material assignments, when the materials are outside the primitive's scope. For that, we just expect the material to be built by something else (it'll be in all our cases), we don't do any additional checks.
- #286
> Fixing infinite recursion when instances and materials are outside the instancer's scope

- build_scripts/build_usd.py
When using `--generator` with `build_usd.py`, this makes it more clear in the output what was selected.
> build_usd: Output what the cmake generator configuration is.

- pxr/imaging/lib/glf/drawTarget.cpp
- pxr/usd/lib/usd/stage.cpp
This wants to get a literal string for the format argument and
then to do the substitution itself.
> Fix format security warnings under clang.

- pxr/imaging/lib/hdSt/indirectDrawBatch.h
This fixes a warning under clang.
> Use override as other things in this file do.

- pxr/usd/lib/usd/usdGenSchema.py
This is part of a continuing effort to make schemaGen friendlier to use.
UsdGenSchema disallows schemas from inheriting from multiple
parents. Currently this error manifests as:
```
ERROR: 'NoneType' object has no attribute 'typeName'
```
Needless to say, this isn't particularly helpful. This commit
changes the error to manifest as follows(given an example schema
defined at /MyC):
```
ERROR: Invalid schema definition at </MyC>
Schemas can only inherit from one other schema at most. This schema inherits from 2 (/MyBase, /Xformable).
See https://graphics.pixar.com/usd/docs/api/_usd__page__generating_schemas.html for more information.
```
> [Usd] Add more informative error message in sg.

- pxr/usd/lib/sdf/primSpec.cpp
- pxr/usd/lib/usd/stage.cpp
- pxr/usdImaging/lib/usdImaging/delegate.cpp
This happens when the result of a comparison is used as the
condition within an if statement in clang (and gcc?).
> Fix warnings about missing parentheses.

- pxr/imaging/lib/glf/shaders/simpleLighting.glslfx
The OSX GLSL compiler doesn't like preprocessor directives like:
#if foo
when the macro "foo" has not been defined. This was showing up in the simple lighting shader when checking a couple of "HD_HAS_xxx" conditions, causing the shader to fail to compile. These check should be of the form:
#if defined(foo)
as all other checks for "HD_HAS_xxx" conditions are in other shaders.
> Fix simple lighting shader to compile under OSX

- pxr/usd/plugin/usdAbc/alembicFileFormat.cpp
hydra to update the display of the geometry until there was some other
edit to the stage.
> Fix a bug where calling Reload on an Alembic file layer would not cause

- cmake/modules/FindAlembic.cmake
The FindAlembic.cmake module now looks for user provided Alembic dir before trying the standard paths. This allows to have a version of Alembic installed, while still being able to build USD against another locally built version.
- #409
> fix for issue 409: FindAlembic now uses the user provided one.

- pxr/base/lib/plug/registry.h
Commit 9ad3c35335a38db94736ab3ee13b6fafa50956c0 changed this from
being a struct to a class. On certain compilers(clang in this case)
it warns on forward declarations in which the declared type doesn't
match the one in the definition.
- None
> [Plug] Update fwd decl.

- cmake/macros/Public.cmake
Ninja and cmake get unhappy when there is a custom command output
and a custom target with the same name resulting in a cyclic
dependency between them. This isn't an issue with cmake's support
for Makefiles.
> cmake: Fix building with ninja.

- cmake/macros/testWrapper.py
- third_party/maya/lib/usdMaya/CMakeLists.txt
- third_party/maya/lib/usdMaya/testenv/UsdMayaAppDirTest/maya_profile/scripts/userSetup.py
- third_party/maya/lib/usdMaya/testenv/testUsdMayaAppDir.py
- third_party/maya/plugin/pxrUsd/CMakeLists.txt
in testWrapper.py, set the $MAYA_APP_DIR env var, so that maya tests run using a default user profile
- ~~https://github.com/PixarAnimationStudios/USD/commit/718780496f8cfd88492a2f54fb783b348b3be5f3~~
- https://github.com/PixarAnimationStudios/USD/pull/209/commits/f75077e557a7a5c15ccf5ea318076e52237e62e8
- We were experiencing some crashes when running the tests on maya-2017, due to some problems with the color-management settings in the user profile
> set $MAYA_APP_DIR before running tests, to use a default maya profile

- third_party/katana/lib/usdKatana/readPrim.cpp
The change allows any parent scope names for materials. Previously it had to be Looks. The behavior can be controlled via an environment variable, and it's turned off by default to maintain current behavior.
None reported.
> [usdKatana] Allowing custom parent scope names for Katana materials.

- pxr/base/lib/tf/scopeDescription.cpp
- pxr/usdImaging/lib/usdImaging/materialAdapter.h
> Fix mismatched tags warnings.

- third_party/maya/lib/usdMaya/usdTranslatorExport.mel
So, in our pr/export_parent_scope pull request (https://github.com/PixarAnimationStudios/USD/pull/223), we accidentally introduced a duplicate MEL function. Looks like we both implemented it, and then when we did a rebase, we didn't pick up the duplicated code. Apologies!
> [maya] remove duplicate usdTranslatorExport_AppendFromTextField mel func

- pxr/imaging/lib/glf/plugInfo.json
The PR add tx to the list of supported textures to fix issue #97 . The conclusion there was to manually maintain the supported texture format lists because listing all the supported formats from OIIO would lead loading the incorrect texture formats using Glf_OIIOImage. (like ptex)
- #97
> [usdImaging] Enabling tx support in imaging.

- pxr/usd/plugin/usdAbc/CMakeLists.txt
- pxr/usd/plugin/usdAbc/alembicUtil.h
- pxr/usd/plugin/usdAbc/alembicWriter.cpp
- pxr/usd/plugin/usdAbc/testenv/testUsdAbcUvWrite.py
- pxr/usd/plugin/usdAbc/testenv/testUsdAbcUvWrite/testUsdAbcUvWrite.usda
The following change modifies the behaviour of the alembicWriter plugin so that it prefers the "st" attribute over the "uv" attribute. When exporting USD from any 3rd party application, the plugins write uvs to the "st" attribute not to "uv".
No issues reported.
> [usdAlembic] Preferring st over uv attribute if present for UV writes.

- pxr/usdImaging/lib/usdImaging/lightAdapter.h
Export more methods from the light adapter class so it can be subclassed in other libraries.
> Export more methods from the light adapter class so it can be subclassed

- build_scripts/build_usd.py
Switch libtiff to download via http
- Some firewalls do not support FTP anymore
- libtiff was the only dependency that was being pulled via ftp, so it reduces the number of protocols required for the build.
> switch libtiff to http download

- pxr/usd/lib/usd/stage.cpp
- pxr/usd/lib/usd/stage.h
- pxr/usd/lib/usd/testenv/testUsdPrims.py
- pxr/usd/lib/usd/wrapStage.cpp
This allows a convenient way to get items in a stage from paths,
whether they are property paths or prim paths.
This was requested on the interest forum a while back, don't have the link handy.
> [Pxr] Add UsdStage::GetObjectAtPath.

- pxr/usd/lib/sdf/assetPathResolver.cpp
- pxr/usd/lib/sdf/testenv/testSdfLayer.py
- pxr/usd/lib/usd/testenv/testUsdStage.py
It was broken when the provided identifier had a colon in it,
which is legal in a posix file path.
e.g.
```python
from pxr import Usd
s = Usd.Stage.CreateInMemory('foo:foo.usda')
s.GetRootLayer().GetDisplayName()
```
Should return `foo:foo.usda`, but currently returns an empty string
- None
> Fix GetDisplayName() for Anonymous Layers.

- cmake/defaults/msvcdefaults.cmake
This commit allows the user to specify the `Boost_USE_STATIC_LIBS` option to disable auto-linking on Windows (`msvcdefaults.cmake` was always forcing linking the dynamic boost libs (dlls) on Windows)
If the option is not set in CMake, the usual behavior does not change.
- #407
> add support for Boost_USE_STATIC_LIBS on Windows. Fixes #407

- third_party/maya/lib/pxrUsdMayaGL/batchRenderer.cpp
- third_party/maya/lib/pxrUsdMayaGL/batchRenderer.h
- third_party/maya/lib/pxrUsdMayaGL/proxyShapeDelegate.cpp
- third_party/maya/lib/pxrUsdMayaGL/shapeAdapter.cpp
- third_party/maya/lib/usdMaya/proxyShape.cpp
- third_party/maya/lib/usdMaya/proxyShape.h
Currently, if using "pure" VP2 selection (ie, MAYA_VP2_USE_VP1_SELECTION is not
set), then if the "softSelectable" attribute is off, the object cannot be
selected by clicking on it in the viewport.
This is because proxyShape attempts to control soft-selection via
MPxSurfaceShape::getShapeSelectionMask().  Unfortunately, the intent of this
function is to control which selection filters the shape responds to, for any
selection (ie, normal + soft selection), and it is only a quirk / bug of
MAYA_VP2_USE_VP1_SELECTION mode that this setting is queried for soft selection,
but not normal selection.
To make the softSelectable attr work in both pure VP2 and
MAYA_VP2_USE_VP1_SELECTION modes, we now check if object-mode soft-selection is
currently on, and if the object is set to be not selectable; …
> [usdMaya] fix for VP2 selection when MAYA_VP2_USE_VP1_SELECTION is off

- pxr/usd/bin/usdedit/CMakeLists.txt
Set the stronger env var in the usdedit tests. Afair, `USD_EDITOR` was provided after the tests were first created, hence the impedance mismatch. 
- #505
> [usdedit] Use stronger env var in tests.

- cmake/defaults/msvcdefaults.cmake
Description of Change(s)
Removing the whitespace on the standards compliant flags to fix build runs which use NMake Makefiles or NMake Makefiles JOM on Windows.
This is against the dev branch.
Fixes Issue(s)
pxr\base\lib\arch\CMakeFiles\arch.dir\flags.make(5) : fatal error U1033: syntax error : '/Zc' unexpected
Cheers
> Removing the whitespace on the standards compliant flags - MSVC

- third_party/maya/lib/usdMaya/JobArgs.cpp
- third_party/maya/lib/usdMaya/JobArgs.h
- third_party/maya/lib/usdMaya/MayaInstancerWriter.cpp
- third_party/maya/lib/usdMaya/MayaMeshWriter_Skin.cpp
- third_party/maya/lib/usdMaya/MayaSkeletonWriter.cpp
- third_party/maya/lib/usdMaya/MayaSkeletonWriter.h
- third_party/maya/lib/usdMaya/shadingModeExporterContext.h
- third_party/maya/lib/usdMaya/skelBindingsWriter.cpp
- third_party/maya/lib/usdMaya/skelBindingsWriter.h
- third_party/maya/lib/usdMaya/usdExport.cpp
- third_party/maya/lib/usdMaya/usdTranslatorExport.mel
- third_party/maya/lib/usdMaya/usdWriteJob.cpp
- third_party/maya/lib/usdMaya/usdWriteJob.h
- third_party/maya/lib/usdMaya/usdWriteJobCtx.cpp
- third_party/maya/lib/usdMaya/util.cpp
- third_party/maya/lib/usdMaya/util.h
This PR adds the option to strip maya namespaces from resulting prim names in the usdExport maya command.
If you have a node in maya named: `|root_node|one:two:nodename`
the default name for the exported prim is: `/root_node/one_two_nodename` (unchanged)
But if this new flag is provided the prim name will be: `/root_node/nodename`
If any dag nodes would result in the same prim path after stripping namespaces, an error will be raised.
issue #126:
- Often in maya, artists use references with different namespaces. Without this flag, there is no way to get exports to have the same hierarchy when exported. This causes problems later on for things like material assignment.
- This also allows exporting an identical hierarchy from a maya scene (rig file) and a referenced version of that file …
> [maya] add stripNamespaces flag to usdExport

- third_party/maya/lib/usdMaya/MayaCameraWriter.cpp
Adds maya camera's shake offset to USD camera aperture offset if shake is enabled.
This documentation indicates that simply adding the values should be sufficient: https://help.autodesk.com/view/MAYAUL/2018/ENU/?guid=GUID-C3EBB008-7DBE-4B9D-B9AC-1DA974CEFE15
- Exported Maya cameras that use shakeEnabled, shakeHorizontal and shakeVertical will not line up with USD camera.
> [usdMaya] fix usdExport to account for camera shake attribute

- pxr/usdImaging/lib/usdImagingGL/hydraMaterialAdapter.cpp
In cases when shader parameters are connected to textures, but no fallbackValue is set, CodeGen fails to generate the right function signature (missing the return type) causing a compilation error. The change uses the type of the input value and sets the fallbackValue to that type's default Value when a fallback value is not authored on the shader.
Nothing reported.
> [HD] Setting up a default fallbackValue for shader parameters when connected.

- third_party/katana/lib/usdKatana/attrMap.cpp
- third_party/katana/lib/usdKatana/readBlindData.cpp
- third_party/katana/lib/usdKatana/readLightFilter.cpp
- third_party/katana/lib/usdKatana/readMaterial.cpp
- third_party/katana/lib/usdKatana/readPrim.cpp
- third_party/katana/lib/usdKatana/utils.cpp
- third_party/katana/lib/usdKatana/utils.h
In the Katana USD plugin this replaces direct calls to the Resolver with use of the pre-resolved path in an SdfAssetPath. This primarily fixes filenames of relative assets from usd files that are not in the current directory.
First patch does the minimal change to fix the bug. Subsequent patches remove any attempt to use the resolver, and then remove redundant or unnecessary flags from the attribute converter function, these are not needed now that the resolver has already been run correctly by Sdf Layer, and correct the behavior in some (obscure?) cases such as arrays of assets.
> Katana plugin asset resolver fixes

- pxr/usdImaging/lib/usdImaging/pch.h
- pxr/usdImaging/lib/usdImaging/valueCache.h
- pxr/usdImaging/lib/usdImagingGL/engine.h
- pxr/usdImaging/lib/usdviewq/pch.h
Remove use of boost noncopyable.
Reduces dependency on boost.
> [UsdImaging] Remove unnecessary boost::noncopyable

- pxr/usd/plugin/usdAbc/alembicReader.cpp
When reading an Alembic file, the generated USD Prim hierarchy is currently affected by the structure of the Alembic file itself. In cases where the Alembic hierarchy consists of an Xform with a single geometry or camera, like so:
```
/Xform xformNameA
/Subd geomNameB
```
The generated USD Prim hierarchy looks like this:
```
/Mesh xformNameA
```
However, if the Alembic hierarchy has an Xform with two or more geometries or cameras:
```
/Xform xformNameA
/Subd geomNameB
/Subd geomNameC
```
The USD Prim hierarchy maintains the same structure as the Alembic hierarchy:
```
/Xform xformNameA
/Mesh geomNameB
/Mesh geomNameC
```
This is problematic in a pipeline that expects assets to maintain a consistent Prim hierarchy regardless of their contents.
This change adds a control, …
> Alembic plugin: Optionally disable parent-xform-as-mesh behavior

- pxr/imaging/lib/hdx/shadowTask.cpp
- pxr/imaging/lib/hdx/taskController.cpp
- pxr/imaging/lib/hdx/taskController.h
The change adds shadow task generation to HdxTaskController and sets up the camera Window Policy so shadows can be rendered via the HdStream backend.
This is useful for people, who want to build their own renderer using the base classes and not rely on feeding the render index from an USD scene.
> [Imaging] Improving shadow support in HdxTaskController

- pxr/base/lib/tf/__init__.py
- pxr/base/lib/tf/testenv/testTf_PyPtrHolder.py
- pxr/usd/lib/ar/testenv/testArDefaultResolver.py
- pxr/usd/lib/pcp/testenv/testPcpOwner.py
- pxr/usd/lib/sdf/__init__.py
- pxr/usd/lib/usd/testenv/testUsdBugs.py
- pxr/usd/lib/usd/testenv/testUsdCreateProperties.py
- pxr/usd/lib/usd/testenv/testUsdEditTarget.py
- pxr/usd/lib/usd/testenv/testUsdMetadata.py
- pxr/usd/lib/usd/testenv/testUsdNotices.py
- pxr/usd/lib/usd/testenv/testUsdPayloads.py
- pxr/usd/lib/usdGeom/testenv/testUsdGeomBBoxCache.py
- pxr/usd/lib/usdGeom/testenv/testUsdGeomCamera.py
- pxr/usd/lib/usdGeom/testenv/testUsdGeomSchemata.py
- pxr/usd/lib/usdGeom/testenv/testUsdGeomXformable.py
- pxr/usd/lib/usdShade/testenv/testUsdShadeShaders.py
- pxr/usd/lib/usdUtils/testenv/testUsdUtilsSparseValueWriter.py
- pxr/usdImaging/lib/usdviewq/arrayAttributeView.py
> [python] removed trailing semicolons

- pxr/usd/lib/ar/resolver.h
- pxr/usd/lib/ar/resolverScopedCache.h
Further reduce dependence on boost in hopes of a brighter future
of magnificent compile times. Standard C++ now provides proper facilities
for making objects non-copyable(`=delete`), and generally provides better error messages
than boost::noncopyable, so we use this.
- None filed, just more cleanup.
> [Ar] Replace boost noncopyable.

- pxr/base/lib/js/pch.h
- pxr/base/lib/js/value.cpp
See message in previous commits of the same type.
- None filed, just cleanup
> [Js] Remove boost noncopyable.

- third_party/houdini/lib/gusd/GEO_IOTranslator.cpp
- third_party/houdini/lib/gusd/GT_PackedUSD.cpp
- third_party/houdini/lib/gusd/GT_PackedUSD.h
- third_party/houdini/lib/gusd/GT_PointInstancer.h
- third_party/houdini/lib/gusd/GT_PrimCache.cpp
- third_party/houdini/lib/gusd/GT_Utils.cpp
- third_party/houdini/lib/gusd/GT_Utils.h
- third_party/houdini/lib/gusd/GT_VtArray.h
- third_party/houdini/lib/gusd/GU_PackedUSD.cpp
- third_party/houdini/lib/gusd/GU_PackedUSD.h
- third_party/houdini/lib/gusd/GU_USD.cpp
- third_party/houdini/lib/gusd/PRM_Shared.cpp
- third_party/houdini/lib/gusd/USD_CustomTraverse.cpp
- third_party/houdini/lib/gusd/USD_CustomTraverse.h
- third_party/houdini/lib/gusd/USD_XformCache.cpp
- third_party/houdini/lib/gusd/UT_Gf.h
- third_party/houdini/lib/gusd/UT_TypeTraits.h
- third_party/houdini/lib/gusd/defaultArray.h
- third_party/houdini/lib/gusd/instancerWrapper.cpp
- third_party/houdini/lib/gusd/meshWrapper.cpp
- third_party/houdini/lib/gusd/plugin.cpp
- third_party/houdini/lib/gusd/primWrapper.cpp
- third_party/houdini/lib/gusd/refiner.cpp
- third_party/houdini/lib/gusd/stageCache.cpp
- third_party/houdini/lib/gusd/writeCtrlFlags.h
- third_party/houdini/plugin/OP_gusd/SOP_usdimport.cpp
- third_party/houdini/plugin/OP_gusd/SOP_usdunpack.cpp
Trying to bring this library in line with the needs of Houdini 17:
* Several changes to packed primitive function signatures
* Support float16 UT_Quaternions and vectors
* Exporting a few symbols and classes needed by H17 plugins. Removing
export claim from GusdDefaultArray which is a header-only template class
and so shouldn't claim to export any symbols
* GEO_IOTranslator accepts usd, usda, or usdc extensions
* GEO_IOTranslator loads proxy and default prims, rather than just proxy
* USD_CustomTraverse intialization invoked by an explicit function call
(which is called from gustInitialize)
* USD_XformCache env var initialization fix, most likely peculiar to the
way that H17 causes this library to be loaded
* Convert uses of HDK_API_VERSION to SYS_VERSION_FULL_INT. This latter
variable is …
> Allow this library to build against Houdini 17

- pxr/imaging/lib/hdx/renderSetupTask.h
This value was subsequently used uninitialized, after being passed onto the
renderPassState, in SyncParams
Ran into this when I was doing memory profiling to try to track down (what turned out to be) an unrelated crash.
Note that, since nothing ever seems to alter HdxRenderTaskParams.stencilEnable, it's possible that the "correct" thing to do may be to remove this parameter from the struct entirely... however, that's not a call I wanted to make.  For now, this at least prevents usage of uninitialized memory.
- stencilEnabled was being set to an essentially random value (which usually evaluated to true)
> renderSetupTask: stencilEnable is not initialized

- pxr/usd/lib/usdGeom/pointBased.cpp
Parallelize extent computation using WorkParallelReduce.
This proved to provide non trivial speedups in one of our
file format plugins which needed to compute extents for every
mesh it was creating (in the realm of 30% on a 150MB asset with
meshes accounting for 30% of its total number of prims).
- Need to use da cores
> [UsdGeom] Speed up extent computation.

- pxr/usdImaging/lib/usdviewq/appController.py
Prim activation/deactivation was printing the wrong message to
the status bar; saying "Activated" when deactivating and
"Deactivating" when activating. This toggles it to do the right
thing.
- None filed.
> [usdview] Fix small UI Bug.

- CMakeLists.txt
Make sure CMAKE_MODULE_PATH passed via command line has precedence over USD.
If there are non standard paths/ installs CMAKE_MODULE_PATH is a much easier route than specifying multiple locations, but USD is currently overwriting any CMAKE_MODULE_PATH passed to it.
> [Cmake] Don't blindly overwrite CMAKE_MODULE_PATH.

- pxr/usd/lib/ar/defaultResolver.cpp
The change updates ArDefaultResolver::AnchorRelativePath so it'll call the virtual IsRelativePath function, instead of explicitly calling ArDefaultResolver::IsRelativePath. This helps developers who want to replace ArDefaultResolver.
> Fixing IsRelativePath call in AnchorRelativePath

- pxr/imaging/lib/hdx/simpleLightTask.cpp
For some fancy shadowing updates we're working on, we need access to both the view + projection parts of the shadow / light projection.  The data structures are actually set up to support this, but at the point where they're populated, it essentially just sets the projection, and sets the view matrix to identity.  This makes the HdxSimpleLightTask properly set the light's view / transform matrix as well.
Of course, in order for this to work properly, the SimpleLight has to be properly set up, so that IT transform + shadow matrices are set up properly / separately.  Currently, nothing in the main code base actually sets the the shadow matrix - but it's possible you folks might have third party code which is, and it may need to be adapted. ie, if you are  passing in a shadow matrix which is …
> [hd] Properly set up both the shadow projection and view matrices

- pxr/base/lib/trace/eventTree.h
Include <functional> for definition of std::function used in this header.
The absence of this include caused a build failure using gcc7.3.
> Add include for std::function in eventTree.h.

- pxr/usdImaging/lib/usdviewq/appController.py
If the user picks a Renderer in usdview, but USD fails to set this renderer
as current (because the runtime environment doesn't support it), display an
error status message, disable the Renderer in the menu, and put the suffix
"(unsupported)" on the menu item (in case the user missed the status
message).
This is a partial replacement for PR #599.
> Better error reporting if the user picks an unsupported renderer in usdview

- pxr/usd/lib/sdf/CMakeLists.txt
- pxr/usd/lib/sdf/fileFormat.cpp
- pxr/usd/lib/sdf/fileFormat.h
- pxr/usd/lib/sdf/fileFormatRegistry.cpp
- pxr/usd/lib/sdf/fileFormatRegistry.h
- pxr/usd/lib/sdf/testenv/testSdfFileFormat.py
- pxr/usd/lib/sdf/wrapFileFormat.cpp
This provides FindAllFileFormats(), returning a set of TfTypes corresponding to the registered formats, and FindAllFileFormatExtensions(), returning the set of all extensions for the registered types.
This has been useful in populating GUIs and will probably have other use cases I haven't imagined yet.
- None filed, just fulfilling my dreams
> [sdf] Add functions for finding registered formats.

- pxr/usd/lib/sdf/data.h
- pxr/usd/lib/sdf/layerStateDelegate.h
Adds export attributes missing from SdlLayerStateDelegate and SdfData. These are necessary to make https://github.com/LumaPictures/usd-qt compile on windows with MSVC
-
> Add missing export attributes to SdfLayerDelegate and SdfData

- pxr/imaging/lib/glf/udimTexture.cpp
- pxr/imaging/lib/glf/udimTexture.h
- pxr/imaging/lib/hdSt/codeGen.cpp
Some changes were not properly merged in from the UDIM pr, like:
- Using unsigned ints for handling pixel counts/dimensions instead of ints.
- Layout data is not getting offset tile ids so that udim tiles will be offset by one.
I also fixed a misleading comment in Codegen.cpp and handled udim images with a null memory request.
> [USD] Missing code / features from the merged UDIM PR.

- third_party/houdini/lib/gusd/GEO_IOTranslator.cpp
This fixes a crash when running ginfo on a USD file. ginfo does not create
any node/channel infrastructure, so trying to call global CH_Manager methods
leads to a crash.
If no CH_Manager exists, use a default of "1" for the sample time.
This fixes Issue #673
> [Houdini] Test for a CH_Manager before calling CH_Manager functions.

- build_scripts/build_usd.py
Added https where possible to download the dependencies. Seems like www.ijg.org doesn't support it.
-
> [build_usd] Use secure https where possible when downloading packages

- pxr/usdImaging/lib/usdImaging/delegate.cpp
Prevent a crash when processing a stage update in hydra in which a prim is
deleted from the stage, and a collection which points directly to that prim
is updated. This would crash while processing the change to the collection,
as it would access the underlying UsdPrim from the index's PrimInfo map
without checking that it is still valid. To get around this, test the
validity of the UsdPrims that show up in the affectedPrims list.
684
> Add a check for a valid UsdPrim when looping over affectedPrims in _RefreshObject

- third_party/houdini/lib/gusd/GT_PackedUSD.cpp
- third_party/houdini/lib/gusd/GT_PrimCache.cpp
- third_party/houdini/lib/gusd/GT_Utils.cpp
- third_party/houdini/lib/gusd/GU_PackedUSD.cpp
- third_party/houdini/lib/gusd/NURBSCurvesWrapper.cpp
- third_party/houdini/lib/gusd/curvesWrapper.cpp
- third_party/houdini/lib/gusd/groupBaseWrapper.cpp
- third_party/houdini/lib/gusd/meshWrapper.cpp
- third_party/houdini/lib/gusd/packedUsdWrapper.cpp
- third_party/houdini/lib/gusd/pointsWrapper.cpp
- third_party/houdini/lib/gusd/primWrapper.cpp
- third_party/houdini/lib/gusd/refiner.cpp
- third_party/houdini/lib/gusd/scopeWrapper.cpp
- third_party/houdini/lib/gusd/writeCtrlFlags.cpp
- third_party/houdini/lib/gusd/xformWrapper.cpp
Include iostream where std::cout or std:cerr are used, and remove using
declarations for these classes in files where they are not used.
These errors showed up trying to build this library against Houdini 17.4.84.
Presumably caused by some combination of include cleanup in the Houdini
and USD baselines.
> [Houdini] Fix for compilation errors caused by missing iostream includes.

- pxr/usd/lib/usd/stage.cpp
It seems like this notification should also get sent during mute/unmute operations.
I ran into this while writing some widgets that need to respond to layer muting, and was surprised it wasn't firing.
> [Usd] Send stage notification change on mute

- third_party/houdini/lib/gusd/treemodel.py
- third_party/houdini/lib/gusd/treeview.py
Houdini include Qt.py in hutil modules.
So i think not good about Houdini version check.
- use Qt.py in hutil modules.
> [Hd] Fix for import modules better than PySide and PySide2

- pxr/usd/lib/usd/attribute.h
This static assert makes it clearer that get cannot be called
with a const T*. Before this, the static assert below would fail, but
the output error is much less clear.
> [Usd] Add better static assert.

- third_party/maya/lib/usdMaya/CMakeLists.txt
- third_party/maya/lib/usdMaya/testenv/UsdExportAsClipTest/UsdExportAsClipTest.ma
- third_party/maya/lib/usdMaya/testenv/testUsdExportAsClip.py
Adds an end to end test that makes sure UsdMaya will export files that can be used as value clips.
This test has been useful in the past to expose a few issues with value resolution in value clips and making sure maya writes all the correct samples. Both discovered issues are resolved now so this test passes with no problems. It simply checks that the samples of certain attributes are identical whether the files are exported as value clips and stitched or as a single usd file.
- no tests for using maya files as value clips
> [usdMaya] Add new test confirming exports can be used as Value Clips

- third_party/houdini/lib/gusd/GT_PackedUSD.cpp
Use SYS_VERSION_FULL_INT define to figure out what version of Houdini is
being built against rather than HDK_API_VERSION. This is a more predictable
value that is always tied exactly to the Houdini version number.
> Change the define used to identify the Houdini version

- third_party/houdini/lib/gusd/meshWrapper.cpp
When refining a USD mesh packed primitive, if we have vertex attributes
and we had to reveress the winding order (i.e. the USD primitive's
orientation attribute is "rightHanded"), we need to reorganize the
vertex attribute data whether we are refining for the viewport or not.
> Issue #631: fixing vertex attributes on rightHanded meshes when refining for the viewport

- pxr/usdImaging/lib/usdviewq/appEventFilter.py
The **AppEventFilter.JealousFocus()** focus method has been updated to also consider the **windowModality()** setting on the widget. The role of this method is to return a flag that indicates whether the widget of interest jealously maintains its input focus. If this method returns True then the auto-focus system (which usually auto-focuses the widget under the cursor as the user moves the mouse around the screen) is _not_ applied. The previous implementation only considered the widget type. However, when plugin views are implemented via PyQt (rather than PySide), all widgets in the plugin view are wrapped in a manner that they are only considered to be instances of QWidget, and deeper instance type information is lost. 
Testing the intended modality of a given widget via the …
> Update JealousFocus() method to handle window modality flag

- third_party/maya/lib/usdMaya/CMakeLists.txt
- third_party/maya/lib/usdMaya/testenv/testUsdExportStripNamespaces.py
- third_party/maya/lib/usdMaya/writeJob.cpp
- third_party/maya/lib/usdMaya/writeJob.h
When exporter strips namespaces is checks if path was already visited and if so raises an error.
However when we also merge transforms and shapes, then it's not an error to map both of them to same primitive.
In addition to checking if path was already visited we check if path is parent or child of visited path.
Exporting to usd with namespace stripping and merging transforms and shapes results in error and does not work.
```
// Error: Multiple dag nodes map to the same prim path after stripping namespaces: |foo|ns:bar - |foo|ns:barShape  -- Runtime Error in _BeginWriting at line 396 of /tmp/source/third_party/maya/lib/usdMaya/writeJob.cpp //
```
> [usdMaya] fix bogus name clash errors when stripping namespaces

- pxr/usd/bin/CMakeLists.txt
- pxr/usd/bin/usddumpcrate/CMakeLists.txt
usddumpcrate wasn't being built by cmake, this change fixes that.
- No filed issues I know of.
> [usd] Add dumpcrate utility to build scripts.

- pxr/usd/lib/ar/packageResolver.h
Register as a ArPackageResolver, not as a ArResolver
Typo in docs
> Fixed typo in package resolver docs

- pxr/usdImaging/lib/usdVolImaging/CMakeLists.txt
- pxr/usdImaging/lib/usdVolImaging/api.h
- pxr/usdImaging/lib/usdVolImaging/field3dAssetAdapter.h
- pxr/usdImaging/lib/usdVolImaging/openvdbAssetAdapter.cpp
- pxr/usdImaging/lib/usdVolImaging/openvdbAssetAdapter.h
- pxr/usdImaging/lib/usdVolImaging/tokens.cpp
- pxr/usdImaging/lib/usdVolImaging/tokens.h
The PR fixes two problems. The first one is to define a separate API macro for the UsdImagingVol, which was using UsdImaging's API macro before. While this won't lead to issues, it goes against the practice seen in other modules. The other improvement is to expose the openvdbAsset and field3dAsset tokens, which are used as bprim types for Hydra Render delegates. Without exposing these tokens, the render delegates have to redefine them.
Refer to the changes in our Arnold Render Delegate to see how exposing the tokens simplifies the code: https://github.com/LumaPictures/usd-arnold/compare/usd_vol_tokens .
None reported.
> [UsdVolImaging] Fixing UsdVolImaging API defines and exposing private tokens

- pxr/usdImaging/lib/usdImaging/pointsAdapter.cpp
Publish the normals attribute or a normals primvar from points primitives through
Hydra using the same code used for curve primitives. Generally the normals of
a points primitive will not be used by a renderer, but it is rather
unexpected that this information isn't even accessible for a render that
does want to use this information (such as to render the points as disks).
> Publish the normals attribute or a normals primvar from points primitives through Hydra

- pxr/usd/plugin/usdMtlx/testenv/testUsdMtlxFileFormat.testenv/NodeGraphs.mtlx
- pxr/usd/plugin/usdMtlx/testenv/testUsdMtlxFileFormat.testenv/baseline/NodeGraphs.usda
Updating the material x test to accommodate for a change in the MaterialX spec: changing the name of the `mix` node's parameter from `mask` to `mix`.
> [USD] Updating material x test to match the latest spec

- pxr/usdImaging/lib/usdImaging/pointInstancerAdapter.cpp
- pxr/usdImaging/lib/usdImaging/pointInstancerAdapter.h
Delegate GetVolumeFieldDescriptors calls to the volume primitive adapter
if the volume is a prototype in a point instancer prim.
This fixes an issue that volume primitives instanced with a point instancer
would not be rendered, because they would report having no fields.
> Delegate GetVolumeFieldDescriptors calls to the volume primitive adapter

- pxr/usdImaging/lib/usdviewq/appController.py
This uses #532 to query the available formats for the open dialog in usdview. This is useful for external consumers of USD who have file format plugins for legacy or otherwise external formats.
> [Usdview] Query available formats for Open

- build_scripts/build_usd.py
Initially aimed to make it work on windows, but subsequently tested / got it working on all 3 platforms: windows, linux (ubuntu), and MacOS 
- build_usd.py fails with --generator=Ninja
> Tweaks to make build_usd.py work with ninja

- pxr/base/lib/arch/pragmas.h
- pxr/base/lib/tf/singleton.h
This addresses the issue referenced in #379(which I propose we close in favor of this PR). 
An example manifestation of this warning is as follows:
```
pxr/base/lib/tf/singleton.h:138:28: note: add an explicit instantiation declaration to suppress this warning if 'pxrInternal_v0_18__pxrReserved__::TfSingleton<pxrInternal_v0_18__pxrReserved__::SdfSchema>::_instance' is explicitly instantiated in another translation unit
return ARCH_LIKELY(_instance) ? *_instance : _CreateInstance();
```
This warning is described in the LLVM bug tracker here: https://reviews.llvm.org/D16396
In our case, afaict, this warning is a false positive, as Tf's singletons are explicitly instantiated in the proper translation unit and won't cause an issue. Rather than suppressing the warning wholesale, this puts a …
> [Tf] Suppress clang warning.

- pxr/usdImaging/lib/usdImaging/CMakeLists.txt
- pxr/usdImaging/lib/usdImaging/pch.h
Removes includes and linkage to Python from usdImaging.
The usdImaging library no longer has any Python-related
code, so these are no longer needed.
> Remove references to Python from usdImaging

- third_party/houdini/lib/gusd/primWrapper.cpp
Allow round tripping of namespaced primvars from USD -> Houdini
geometry -> USD. To do this, we convert the USD attribute name with the
namespace separator into a form that follows the rules for Houdini
geometry attributes using the UT_VarEncode class. This class is only
available in Houdini 17.5 and above, so this attribute name encoding is
only enabled when building against Houdini 17.5 or greater.
When SOP geometry is being converted back to USD attributes, the decode
method of UT_VarEncode is used to turn any encoded attribute names back
into their original form.
> Allow round tripping of namespaced primvars from USD -> Houdini geometry -> USD

- pxr/usd/plugin/usdAbc/CMakeLists.txt
- pxr/usd/plugin/usdAbc/alembicReader.cpp
- pxr/usd/plugin/usdAbc/alembicUtil.h
- pxr/usd/plugin/usdAbc/alembicWriter.cpp
- pxr/usd/plugin/usdAbc/testenv/testUsdAbcFaceset.py
- pxr/usd/plugin/usdAbc/testenv/testUsdAbcFaceset/original.usda
This work is a continuation of Adam Ferrall-Nunge's work in #219, which added support for Alembic facesets to USD. At that time they were represented as Faceset data on the parent prim, which was subsequently read by pxrUsdIn and expanded back to faceset nodes. That PR was never accepted because UsdGeomSubset was introduced which became the more appropriate choice for representation of Alembic Facesets.
To a large extent this simplified the problem: The exact same hierarchy is maintained between Alembic and USD with only the type changing (Alembic "Faceset" to USD "GeomSubset"). pxrUsdIn already has support for GeomSubset, so there was no need to make any pxrUsdIn changes for Katana.
This is a rebasing of https://github.com/PixarAnimationStudios/USD/pull/754 onto dev.
I've added a new …
> Add faceset support to usd dev

- pxr/imaging/lib/hdx/taskController.cpp
- pxr/imaging/lib/hdx/taskController.h
- pxr/usdImaging/lib/usdImagingGL/engine.cpp
This allows HdxTaskController::TestIntersection to return results that are closest (by depth) to the camera, instead of just closest to the camera center.
Exposing this would be useful for AL_USDMaya.
> [hdx] TaskController::TestIntersections allows selection by nearestToCamera

- pxr/usdImaging/lib/usdImagingGL/engine.h
When upgrading AL_USDMaya to USD 19.01, see PR [here](https://github.com/AnimalLogic/AL_USDMaya/pull/133), we (actually, our friends at Luma who did the work) ended up calling _UpdateHydraCollection (see [here](https://github.com/AnimalLogic/AL_USDMaya/blob/0a119b251ea11c3b4d91c5aa6551c6c300312009/lib/AL_USDMaya/AL/usdmaya/nodes/Engine.cpp#L63))
This worked without problems in Linux, but failed on Windows due to the method's symbol not being exported
- Add DSO export visibility to UsdImagingGLEngine._UpdateHydraCollection in usdImagingGL/engine.h
> Add DSO export visibility to UsdImagingGLEngine._UpdateHydraCollection 

- pxr/usd/lib/usdGeom/pointBased.cpp
This brings ComputeExtent for transforms inline with the
changes made in #588. Given the similarity of the implementations
this also abstracts them into a template function.
- None filed. This brings a similar performance win, and consolidates the code.
> [UsdGeom] Speed up extent computation (redux)

- pxr/usdImaging/lib/usdviewq/appController.py
Fixes a bug that would reset the current frame when the start/end frame widgets loses focus and no changes were made.
> [usdview] Added a check to _rangeBegin(End)Changed to only update if the value changes

- third_party/houdini/lib/gusd/USD_DataCache.cpp
- third_party/houdini/lib/gusd/boundsCache.cpp
- third_party/houdini/lib/gusd/stageCache.cpp
- third_party/houdini/lib/gusd/stageCache.h
Adding support for the explicit addition of stages to the GusdStageCache. The use case here is that we have in-memory stages (with anonymous root layers) from which we would like to construct USD packed primitives. Rather than having the GusdStageCache construct new (masked) stages from these in-memory stages, it makes more sense to just tell the cache that these full stages are already in memory.
Also had to fix the cache invalidation code to properly deal with anonymous layer identifiers so that these in-memory stages can be modified, and the cache properly invalidated in response.
> [Houdini] Provide support for adding in-memory stages to the GusdStageCache

- third_party/houdini/lib/gusd/GU_PackedUSD.cpp
- third_party/houdini/lib/gusd/GU_PackedUSD.h
As of the next major Houdini release, GU_PackedImpl contains a bounding box object for caching a 
calculated bounding box. Therefore, if building against this future release of Houdini:
* Removed redundant bounding box cache from GusdGU_PackedUSD, since it
can use the one in GU_PackedImpl, and getBounds shouldn't use the cache.
* Made sure that GusdGU_PackedUSD::getBounds always initializes the box,
even if returning false
For all currently shipping versions of Houdini, the behavior of this code is unchanged.
> [Houdini] Changes for future Houdini release related to caching packed primitive bounding boxes

- build_scripts/build_usd.py
Mostly handy if debugging build_usd.py itself - but could be handy in other circumstances. And it makes sense not to swallow the traceback if verbosity is this high.
- Tracebacks swallowed even on high verbosity
> [build_usd] print tracebacks on error if verbosity >= 3

- pxr/imaging/lib/glf/simpleLightingContext.cpp
An instance of GlfSimpleShadowArray created by GlfSimpleLightingContext was missing a TfCreateRefPtr wrapper which caused it to be leaked. In the pxrUsd Maya plugin, this happened on every frame because of a temporary lighting context used to retrieve lighting settings from Maya.
By the way, is TfRefPtr here to stay, or can it be replaced with boost or standard pointers in the future? TfCreateRefPtr is unfortunately very easy to miss.
> [Glf] Fixed an empty GlfSimpleShadowArray instance being leaked.

- cmake/macros/Private.cmake
- pxr/CMakeLists.txt
- pxr/pxrConfig.cmake.in
Fixes the installation of the pxrConfig.cmake file for both static and shared USD build variants
- Adds a mechanism to export PXR_STATIC when required
- Adds DbgHelp and shlwapi to the Windows static build
- pxrConfig.cmake unconditionally includes cmake scripts that describe the libraries, so it is necessary to ensure associated cmake files are also exported properly as part of the installation process
- fix selection logic around monolithic and non-monolithic build when generating config files
- pxrConfig.cmake should enable find_package(pxr) and remove the need to write ad hoc FindUSD.cmake scripts. pxrConfig.cmake references files that were not actually exported, making the config file non-functional
- pxrConfig.cmake targets were not set up for a static build at all
- Does not …
> Fix pxrConfig.cmake

- pxr/usd/lib/usdSkel/animMapper.cpp
- pxr/usd/lib/usdSkel/animMapper.h
- third_party/maya/lib/usdMaya/translatorSkel.cpp
This fixes the maya import of skin bindings that set an explicit joint order
- https://github.com/PixarAnimationStudios/USD/issues/789 (partially - HdxComputation is not fixed)
> [usdSkel] [usdMaya] fix skin import with explicit joint orders

- pxr/usd/lib/usd/usdGenSchema.py
Ran into another unfortunate error handling in schemaGen, this cleans it up.
Scenario: An unknown type is specified on an attribute in a schema. For example
```
#usda 1.0
(
subLayers = [
@usd/schema.usda@
]
)
over "GLOBAL" (
customData = {
string libraryName = "contrived"
string libraryPath = "."
string libraryPrefix = "c"
string tokensPrefix = "ctrvd"
}
){
}
class "something" (
doc = "...."
inherits = </Typed>
)
{
uniform boool b = false (doc = "")
}
```
The error before this change:
```
ERROR: <pxr.Sdf.ValueTypeNames object at 0xdeadbeef>
```
The error after this change:
```
ERROR: Code generation requires that all attributes have a known
type (</something.b> has type 'boool', which is not a member of Sdf.ValueTypeNames.)
```
- No filed issues
> [Usd] Clean up schemaGen error message.

- pxr/usdImaging/lib/usdviewq/appController.py
- pxr/usdImaging/lib/usdviewq/frameSlider.py
The three PR's I've submitted tonight will allow me to submit a final PR for the current frame feature once they have been merged into dev!
* Split _updateOnFrameChange into _updateOnFrameChange and _updateOnFrameChangeFinish
* Allows us to differentiate between what we want to update whilst the frame is changing (playing/scrubbing) and what we want to update when the frame change has finished.
* Removes the need for the refreshUI variable.
* Simplified the FrameSlider class
* Reverted to using Qt's logic for scrubbing/tracking which improves accuracy and performance.
* In doing so, fixed a minor bug that was causing extra UI updates whilst scrubbing.
* If the action of scrubbing happens towards the start or end, isSliderDown returns False rather than True.
* Only using the class to …
>  [usdview] Split _updateOnFrameChange logic. Simplified the FrameSlider class.

- cmake/modules/FindGLEW.cmake
- cmake/modules/FindPTex.cmake
This PR improves the `FindGLEW` and `FindPTex` cmake modules by allowing searching in custom `lib64` directories for GLEW and PTex include subfolder.
-
> Better ptex glew find

- pxr/imaging/lib/garch/CMakeLists.txt
Add ${X11_LIBRARIES} as being required by the garch library. There are calls
to various glX methods in this library. When building USD itself it seems
fine that the X11 libraries are not explicitly linked in, but when building
other libraries that link in garch, specifically when using the "gold" linker
(the standard gcc linker works fine) it complains about undefined symbols in
garch that should come from the X11 libs. It is not clear why "gold" behaves
differently in this situation, but I can't see any harm in explicitly calling out this
dependency in garch, and it fixes our build issue.
> Add ${X11_LIBRARIES} as being required by the garch library

- pxr/usd/lib/ar/wrapResolver.cpp
Simply add _ArResolver::RefreshContext_ method to _wrapResolver.cpp_
https://github.com/PixarAnimationStudios/USD/issues/694
> [Ar] Python bindings for resolver RefreshContext

- pxr/base/lib/vt/array.h
- pxr/base/lib/vt/testenv/testVtCpp.cpp
Discussed this one offline with @gitamohr , seems like a nice addition. Its useful
for us when constructing VtArrays from foreign data sources (Maya APIs, etc) which
return `T*`s or `vector<T>`s.
VtArray mimics much of std::vector's interface. This adds
iterator construction, which had been previously omitted.
In the past, VtArray supported dimensions, which made such
construction unwieldy; it is now a flat container, making
this a viable option.
- None filed
> [Vt] Add iterator construction for arrays.

- pxr/imaging/lib/hd/changeTracker.cpp
- pxr/imaging/lib/hd/tokens.h
- pxr/usdImaging/lib/usdImaging/basisCurvesAdapter.cpp
- pxr/usdImaging/lib/usdImaging/meshAdapter.cpp
- pxr/usdImaging/lib/usdImaging/pointsAdapter.cpp
This is a greatly simplified replacement for PR #743.
After discussions with the USD team, it was decided that velocities does not need its own dirty bit or dedicated change tracker or value cache functions. Instead, use the pointsDirty bit, and publish it as a regular primvar. Using the pointsDirty bit is reasonable because the velocities attribute, according to USD standards, should be published at the same time samples where the points attribute is published.
> Expose velocities attribute to render delegates

- pxr/usd/plugin/usdAbc/alembicReader.cpp
Alembic 1.7.9 introduced an API change in `Alembic::AbcCoreOgawa::ReadArchive`: a new boolean argument is required. This PR conforms to the new function signature for Alembic >= 1.7.9
The behavior of `Alembic::AbcCoreOgawa::ReadArchive` can be configured by a new environment variable: `USD_ABC_READ_ARCHIVE_USE_MMAP`
By default, `Alembic::AbcCoreOgawa::ReadArchive` keep on using the pre 1.7.9 behavior
- #667
> Fix compatibility for AbcCoreOgawa::ReadArchive with Alembic>=1.7.9

- pxr/usdImaging/lib/usdviewq/__init__.py
- pxr/usdImaging/lib/usdviewq/appController.py
* Added help strings to startFrame and lastFrame.
--ff FIRSTFRAME       Set the first frame of the viewer
--lf LASTFRAME        Set the last frame of the viewer
--cf CURRENTFRAME     Set the current frame of the viewer
* Refactored setFrame to _setFrameIndex
* Removed the closestFrame lookup - as far as I'm aware this does nothing of value as closestFrame always equals frame.
* This has given us a speed increase on playback - the closestFrame lookup iterated over the entire _timeSamples list every time the frame changed.
* Removed the need for the forceUpdate variable.
* Re-purposed setFrame to be a simple wrapper that finds a frameIndex and calls _setFrameIndex.
* Found bug where resetting of the timeline would also not update the dataModel - so the value on the timeline and what was …
> [usdview] Added currentFrame command line argument

- third_party/maya/lib/usdMaya/shadingModePxrRis.cpp
- third_party/maya/lib/usdMaya/translatorRfMLight.cpp
- third_party/maya/lib/usdMaya/translatorUtil.cpp
- third_party/maya/lib/usdMaya/translatorUtil.h
Turns UsdMayaTranslatorUtil::CreateShaderNode into a wrapper over the shadingNode command
The docs said it was intended to mimic this command, but it was lacking some
functionality; in theory, we might have been able to add the (known) missing
functionality, but past experience has shown attempting to replicate this
command not worth the small efficiency gain by avoiding the string conversions
needed by mel commands.
Also eliminated ConnectDefaultLightNode, since it was also mimicking this command
- shadingNodes not showing up in the hypershade
- texture nodes not being hooked into the color management system
> [usdMaya] make UsdMayaTranslatorUtil::CreateShaderNode use shadingNode

- pxr/usdImaging/lib/usdImagingGL/engine.cpp
Fixes the overload of the UsdImagingGLEngine constructor that took arguments
It did not call _InitGL, like the no-arg constructor. This resulted in an
error: `GlfContextCaps has not been initialized`
- error when calling UsdImagingGLEngine constructor w/ args
> [usdImagingGL] fix UsdImagingGLEngine constructor w/ args

- pxr/usdImaging/lib/usdviewq/appController.py
- pxr/usdImaging/lib/usdviewq/debugFlagsWidget.py
- pxr/usdImaging/lib/usdviewq/qt.py
Newer versions of PySide (ie, 5.11) have changes that break existing usdview code.
This fixes these issues, while still maintaining backwards compatibility with older versions.
Note that I've closed https://github.com/PixarAnimationStudios/USD/pull/783 in favor of this
- Usdview - reset view doesn't work with newer PySide (5.11)
- Usdview - debug flags window doesn't work with newer PySide (5.11)
> Fixes for newer versions of pyside

- pxr/usd/lib/usdGeom/primvar.cpp
Added support for indexed primvar values of type `uint[]`.
_testUsdGeomPrimvar.py_ could be extended to include a test for this in _test_PrimvarsAPI()_ but not sure if that's necessary. 
```
uint_array = gp_pv.CreatePrimvar('uint_array', Sdf.ValueTypeNames.UIntArray)
uint_values = Vt.UIntArray([3, 1, 4])
uint_array.Set(uint_values)
indices = Vt.IntArray([0, 1, 2, 1, 2, 0])
uint_array.SetIndices(indices)
self.assertFalse(uint_array.ComputeFlattened() is None)
```
> [usdGeom] added support for indexed uint primvar values

- pxr/base/lib/tf/pyContainerConversions.h
- pxr/base/lib/tf/span.h
- pxr/base/lib/work/filter.h
- pxr/imaging/plugin/hdEmbree/renderBuffer.cpp
- pxr/imaging/plugin/hdEmbree/renderBuffer.h
- pxr/usd/lib/pcp/testenv/testPcpIterator.cpp
- pxr/usd/plugin/usdAbc/alembicReader.cpp
- pxr/usd/plugin/usdAbc/alembicWriter.cpp
Were a few leftover warnings when I tried to build with gcc-6 / c++14... but not many, so I just fixed them up and bundled into a PR.
- Sign comparison warnings with gcc-6 / c++14
- Unused function warnings with gcc-6 / c++14
> Fixes for building with gcc-6 / c++14 with PXR_STRICT_BUILD_MODE

- third_party/maya/plugin/pxrUsd/plugInfo.json
- third_party/maya/plugin/pxrUsdPreviewSurface/plugInfo.json
- third_party/maya/plugin/pxrUsdTranslators/plugInfo.json
The maya usd-plugins are mostly there just to provide metadata (so the
associated maya plugins can be found and loaded); however, as currently
configured, if you try to Load() them, they error.  This creates ugly
error messages in, ie, AL_USDMaya, which pre-emptively tries to load all
usd plugins.
This is because they are configured as python plugins, but there is no
associated python module. Setting them to resource plugins removes the
error.
- Error when loading the maya usd-plugins
> prevent error when loading usdMaya usd-plugins

- pxr/imaging/lib/hdx/colorizeTask.cpp
If an HdxColorizeTask has not been configured with an aov buffer, before
doing an early exit from the Execute method, set the _converged flag to
true so this task isn't left in an unconverged state forever.
#874
> Always mark unconfigured HdxColorizeTasks as converged on an Execute call

- cmake/modules/FindMaya.cmake
Formerly, FindMaya.cmake assumed that MAYA_LOCATION on osx was set to
the top level installation dir, ie:
/Applications/Autodesk/maya2018
However, official Autodesk sources indicate that MAYA_LOCATION should
include Maya.app/Contents, ie:
/Applications/Autodesk/maya2018/Maya.app/Contents
For backward compatibility (and maximum convenience), FindMaya.cmake
still supports pointing at the top-level installation dir, but pointing
inside of Maya.app/Contents is now checked first.
Formerly, if MAYA_LOCATION was set to:
/Applications/Autodesk/maya2018/Maya.app/Contents
...but a maya 2019 install existed, at:
/Applications/Autodesk/maya2019
...then MAYA_BASE_DIR would end up pointing at the 2019 install, but
MAYA_LOCATION would stay pointing at 2018.  This would result in some
things pointing at …
> fix usage of MAYA_LOCATION when building on osx

- pxr/usd/lib/usd/usdGenSchema.py
Pretty non-invasive change to provide a quiet mode to usdGenSchema. This would be really useful to have. While this could be done with whatever script is calling it, it gives users a much simpler interface for doing so at a low cost to us(in terms of code complexity etc).
- None filed.
> [Usd] Provide a quiet mode for usdGenSchema.

- third_party/houdini/lib/gusd/CMakeLists.txt
Added usdSkel to required libraries in gusd cmake .
- Fixed gusd missing usdSkel dependency [#826]
> gusd: fixed missing usdSkel dependency

- pxr/usd/lib/usd/CMakeLists.txt
- pxr/usd/lib/usd/testenv/testUsdSchemaBasePy.py
- pxr/usd/lib/usd/wrapSchemaBase.cpp
- pxr/usd/lib/usdGeom/testenv/testUsdGeomPrimvar.py
- pxr/usd/lib/usdGeom/testenv/testUsdGeomXformable.py
- pxr/usd/lib/usdGeom/wrapPrimvar.cpp
- pxr/usd/lib/usdRi/testenv/testUsdRiSplineAPI.py
In wrapSchemaBase, replace the __getattribute__ method as was already being
done in wrapObject. This overloaded __getattribute__ actually allows any of
the UsdSchemaBase APIs to be called (as all of the methods at this level can
still return useful information). But its purpose is to block calls to APIs
defined on subclasses.
Provided similar protection for UsdGeomPrimvar, which is an odd case that is
like a schema class, but operates on a single attribute and so is not derived
from SchemaBase.
Added some test cases, including an explicit test of issue #872, a crash when
calling UsdGeom.Xformable().ClearXformOpOrder(). TestUsdRiSplineAPI had to be
updated because a test in there was not expecting the RuntimeException from
an invalid object.
- #872
> Prevent crashes when calling methods on invalid Usd.SchemaBase objects

- pxr/imaging/lib/hd/renderDelegate.cpp
- pxr/imaging/lib/hd/renderDelegate.h
- pxr/imaging/lib/hd/renderThread.cpp
- pxr/imaging/lib/hd/renderThread.h
- pxr/imaging/plugin/hdEmbree/renderDelegate.cpp
- pxr/imaging/plugin/hdEmbree/renderDelegate.h
- pxr/imaging/plugin/hdEmbree/renderer.cpp
- pxr/imaging/plugin/hdEmbree/renderer.h
- pxr/usdImaging/lib/usdImagingGL/engine.cpp
- pxr/usdImaging/lib/usdImagingGL/engine.h
- pxr/usdImaging/lib/usdImagingGL/wrapEngine.cpp
- pxr/usdImaging/lib/usdviewq/appController.py
- pxr/usdImaging/lib/usdviewq/mainWindowUI.ui
- pxr/usdImaging/lib/usdviewq/stageView.py
Adding new APIs to the render delegate (exposed through the UsgImagingGLEngine)
to pause and resume a render (if supported). Also added an API to get a status
message from the render delegate that can be presented to the user to give some
indication of the progress of the render.
Added implementations of these APIs to the embree delegate, which uses matching
new methods on HdRenderThread to assist with the pause and resume operations.
Added a Pause menu item to usdview, and display the render status message in
the upper right hand corner below the render delegate name.
> Adding new APIs to the render delegate for pause, resume, and getting status

- pxr/imaging/lib/glf/oiioImage.cpp
the non-ROI get_pixels overloads were removed in this version, and USD was
still using it, despite the fact that it was deprecated.
This adds a version switch, so that the ROI version is used if available
- Building against OpenImageIO >= 1.9.1 failed
> fix for OpenImageIO >= 1.9.1

- pxr/imaging/lib/hd/timeSampleArray.h
slipped through because it was in a template that's not used by core
(but is by HdPrman)
- building renderman-22 plugin with PXR_STRICT_BUILD_MODE enabled
> [imaging] fix another sign compare issue

- pxr/base/lib/tf/makePyConstructor.h
- pxr/usd/lib/usd/object.h
- third_party/houdini/plugin/OP_gusd/OBJ_usdcamera.cpp
- third_party/houdini/plugin/OP_gusd/ROP_usdoutput.cpp
This cleans out usage of boost macros in USD. It hasn't tackled the preprocessor macros yet, as thats a big problem that will require quite a bit of work.
- None filed.
> Remove Some Boost Usage

- pxr/usd/lib/usd/CMakeLists.txt
Some C++ tests were not being run by ctest due to missing registration.
> [usd] Register missing C++ unit tests.

- pxr/usdImaging/lib/usdImagingGL/engine.h
On windows classes derived from UsdImagingGLEngine don't have export properly set for protected method.
- Fix windows build of AL plugin and USD dev.
> Missing export for Windows build of classes based on UsdImagingGLEngine

- pxr/imaging/plugin/hdEmbree/renderer.cpp
If Embree fails to validate the requested AOVs, mark all buffers as 
converged so the render will exit. Also raise a runtime error indicating
that the render will not complete.
- After invoking the Embree render delegate with unsupported buffer formats (asking for 16bit float color values, for example), the delegate would never reach a converged state even though it wouldn't actually be doing any rendering.
> If Embree fails to validate the requested AOVs, mark all buffers as converged

- pxr/imaging/lib/hdSt/codeGen.cpp
MESA AMD Vega drivers failed with the extra ';' in GLSL. 
Seen on Ubuntu.
- Filed as Pixar-internal issue #USD-5434
> MESA AMD. Fixed syntax arror with ';' after function body.

- pxr/imaging/lib/hdSt/CMakeLists.txt
Domelight glslfx is not installed as part of HdSt, the PR addresses this issue.
> [HdSt] Installing domeLight.glslfx.

- pxr/usd/lib/usdSkel/bakeSkinning.cpp
In this block of code, it is possible to make a call into an invalid UsdSkelAnimQuery object. This results in error messages being generated for no reason. I'm not certain that calling SetMightBeTimeVarying(false) if the anim query is invalid is the right thing to do.
This error was being triggered when calling BakeSkinning on a scene containing skeletons with a restTransforms attribute.
> Adding a validity check on a UsdSkelAnimQuery object before using it

- pxr/usd/lib/usdSkel/bakeSkinning.cpp
Fix crash in BakeSkinning caused by multiple threads populating a shared map object at the same time.
Pre-populate the shared map before giving the mutliple threads access to it.
- I believe this fixes the crash in #952, though the geometry still disappears after calling BakeSkinning.
> Fix crash in BakeSkinning

- cmake/modules/FindRenderman.cmake
- third_party/renderman-22/shaders/CMakeLists.txt
the building of the renderman-22 plugin made use of the RENDERMAN_LOCATION
var, which is not guaranteed to be set by FindRenderman.cmake; instead,
directly export RENDERMAN_BINARY_DIR, and use that to find oslc
- error building renderman plugin if RMANTREE or RENDERMAN_LOCATION supplied only via environment variable
> FindRenderman.cmake: export RENDERMAN_BINARY_DIR, use it to find oslc

- pxr/imaging/lib/hgiGL/CMakeLists.txt
- pxr/usdImaging/lib/usdAppUtils/CMakeLists.txt
[imaging, usdImaging] Fix PXR_ENABLE_GL_SUPPORT=FALSE builds.
https://github.com/PixarAnimationStudios/USD/issues/972
> [imaging, usdImaging] Fix PXR_ENABLE_GL_SUPPORT=FALSE builds.

- pxr/imaging/lib/glf/diagnostic.cpp
- pxr/imaging/lib/hgiGL/diagnostic.cpp
Run usdview with Storm renderer. Enable of one those AOVs: normal, primvars:st, primId.
Windows10, AMD Radeon VII (19.8.1 driver)
"gluErrorString" in case of unknown error passed to it returns nullptr, which passed then to "std::ostream::operator<<" which is calling "strlen" on input pointer. "strlen" in turn, according to the standard, do not check the input pointer and immediately dereference it
- Add check for returned errorString
Surely the main problem here in those AOVs that does not work for some reason on my machine (I have not looked into why). But we must not allow the possibility of such thing as nullptr coming from gluErrorString to crash whole application.
Initially, I experienced this crash in hgiGL module only, but there is the same function in glf module. So I just added …
> Fix crash in case of unknown error passed to gluErrorString

- pxr/imaging/lib/hd/sortedIds.cpp
Validate _afterLastDeletePoint before accessing an array element pointed by it.
- Debug assert on Windows
- Undefined behavior in release build
```
Hd_SortedIds sortedIds;
sortedIds.Insert(SdfPath("/Test2"));
sortedIds.Insert(SdfPath("/Test1"));
sortedIds.Remove(SdfPath("/Test2"));
sortedIds.Remove(SdfPath("/Test1")); // Crash
```
> Fix out of range access in Hd_SortedIds

- pxr/usd/lib/sdf/textFileFormat.cpp
Adds an optional filesize check to textFileFormat that will print a warning if a text layer is loaded that is larger than the specified size in megabytes. This has been really useful for early detection of layers that are accidentally delivered as ascii instead of crate.
The default is 0, which disables the check and maintains the existing behavior of textFileFormat.
> Adds USDA_FILESIZE_WARNING setting

- third_party/katana/plugin/pxrUsdIn/pxrUsdIn.cpp
Fixes the computation of `geometry.instanceSource` paths for nested instances (that is, `instance` locations which are themselves nested inside other `instance source` locations).
- #1014
> [katana] Fix broken geometry.instanceSource attrs with nested instancing

- pxr/imaging/plugin/hdEmbree/CMakeLists.txt
Same motivation and changes as in https://github.com/PixarAnimationStudios/USD/commit/a29529b44b608a4fa2dffd77826444614860ff37
>  Fix TBB library linkage in hdEmbree

- pxr/imaging/lib/glf/plugInfo.json
- pxr/imaging/lib/glf/plugInfo_NoOIIO.json
Glf_StbImage. Added 'jpeg' extension for Glf_StbImage as it already supports 'jpg'
- Allows .jpeg files to be loaded instead of rendering as black/missing texture data.
> Glf_StbImage. Added 'jpeg' extension alongside 'jpg'

- pxr/usdImaging/usdImaging/meshAdapter.cpp
If a mesh is already known to have time-varying topology, don't bother looking at geometry subsets for animation.
The _IsVarying method will actually clear the topology dirty bit, hiding the time varying topology if there are non-animated subsets.
- #1044
> Fix a bug where time-invariant geometry subsets would mask time-varying topology from Hydra.

- pxr/usd/usdGeom/CMakeLists.txt
- pxr/usd/usdGeom/imageable.cpp
- pxr/usd/usdGeom/testenv/testUsdGeomImageable.py
- pxr/usd/usdGeom/testenv/testUsdGeomImageable/AllInvisible.usda
Fix a bug in UdsGeomImageable::MakeVisible, in which the recursive setting
of the visibility attribute to "inherited" would only be done to the invisible
ancestor prim closest to the root. If other ancestors were also marked as
invisible (redundantly, but legally) the original prim would not end up
being visible.
Reversed the order of a conditional inside the recursive _MakeVisible function so
that the setting of the visibility attribute to "inherited" on ancestors is not short
circuited after the first ancestor has this attribute changed.
The provided test case will fail without this change. The prim will not be visible
after calling MakeVisible on it.
> Fix a bug in UdsGeomImageable::MakeVisible

- pxr/imaging/pxOsd/refinerFactory.cpp
usdview emits warnings when UsdGeomMesh's FaceVaryingLinearInterpolation attribute is set with the valid values "cornersOnly" or "cornersPlus2", i.e.:
Warning: in GetOptions at line 142 of src/pxr/imaging/lib/pxOsd/refinerFactory.cpp -- Unknown face-varying boundary interpolation rule (cornersOnly) (...)
This change adds the two missing conditions to the conversion of attribute values to corresponding OpenSubdiv options.
> Fixed usdview warnings with valid UsdGeomMesh face-varying options

- build_scripts/build_usd.py
Add detection for VS2019, and logic for the new syntax in cmake for VS2019 generators. The boost toolset is detected automatically for vs2019, so it is not necessary to specify the toolset in the build script.
- https://github.com/PixarAnimationStudios/USD/issues/1041
> Update build script to support VS2019 building

- pxr/usdImaging/usdImaging/meshAdapter.cpp
When getting the indices attribute from a UsdGeomSubset, pass in the current
UsdTimeCode, otherwise the default value will always be returned (or no value
if a default value isn't explicitly authored).
Add the current time code to the call that loads the indices attribute value.
- #1058
> Use the current UsdTimeCode to get geometry subset indices

- cmake/defaults/gccdefaults.cmake
- pxr/base/arch/pragmas.h
- pxr/base/plug/wrapRegistry.cpp
- pxr/base/tf/wrapFunction.cpp
- pxr/base/tf/wrapNotice.cpp
- pxr/base/tf/wrapTestTfPython.cpp
- pxr/base/vt/wrapValue.cpp
- pxr/usd/ndr/wrapFilesystemDiscovery.cpp
- pxr/usd/sdf/wrapCopyUtils.cpp
- pxr/usd/usd/wrapFlattenUtils.cpp
- pxr/usd/usd/wrapPrim.cpp
- pxr/usd/usdUtils/wrapDependencies.cpp
- pxr/usd/usdUtils/wrapFlattenLayerStack.cpp
This is an alternative solution to the same problem addressed by:
Locally disable placement-new warnings in later versions of gcc.
898b8c1
After discussion (#1074), we decided that the best solution would be to globally disable
this for the affected combo of gcc + boost versions, since newer
versions of boost are not affected.
- Building with PXR_STRICT_BUILD_MODE + gcc-6 + boost-1.61
> gcc: disable placement-new warnings for boost<1.62

- pxr/imaging/lib/hdSt/glslProgram.cpp
Dump shader source to std::cout on link failure if relevant debug flag is set.
- Issue #1017
> HDST_DUMP_FAILING_SHADER_SOURCE debug flag does not dump attached shader source on link failure.

- pxr/imaging/lib/glf/imageRegistry.cpp
- pxr/usd/lib/usdUtils/complianceChecker.py
so we can use, ie, .PNG, .TIF, etc
oiio already can handle this, and Glf_StbImage::_GetFilenameExtension() already converts to lowercase as well
- Loading of .PNG, .TIF, etc (ie, non-lower-case extensions)
> [imaging] make image extension case-insensitive

- pxr/imaging/garch/glPlatformDebugWindowWindows.cpp
This allows a GarchGLDebugWindow to be created on Windows as well.
- _callback is initialised
- _hInstance used as intended
- Fixed _MsgProc to call DefWindowProc during window creation
- Garch_GLPlatformDebugWindow aborted during Init() on Windows
> [garch] Fix GarchGLDebugWindow window creation

- pxr/usdImaging/usdImaging/delegate.cpp
Changes the usdImaging delegate to deliver a proper single value instead of current return of GfVec3f[2] or float[2] when the ExtractXXX function fails for displayColor, displayOpacity, and widths.
.
> [usdImaging] Fix default values for displayColor, displayOpacity, and widths

- build_scripts/build_usd.py
- cmake/defaults/Packages.cmake
- pxr/imaging/glf/CMakeLists.txt
See discussion in https://groups.google.com/d/msg/usd-interest/hmb7ZVVtscY/DmqNROd8BwAJ
> [build_scripts, cmake, glf] Remove OpenEXR from default dependencies.

- pxr/base/arch/attributes.h
- pxr/base/tf/preprocessorUtils.h
- pxr/usd/ar/asset.h
- pxr/usd/sdf/fileFormat.h
Submitting these changes on behalf of @e4lam.
From a clang-cl project that uses a pre-built USD library (with MSVC, but that's fine because they're ABI compatible). A few source header adjustments that clang complained about:
* pxr/base/tf/preprocessorUtils.h: Replace uses of ARCH_OS_WINDOWS with ARCH_COMPILER_MSVC because clang-cl's preprocessor is better. This fixes many compiler errors with the use of boost cpp.
* pxr/usd/sdf/fileFormat.h: Remove SDF_API from "= delete" methods because it doesn't make sense to export deleted methods. I'm surprised that the other compilers allow this.
* pxr/usd/ar/asset.h: Remove AR_API from "= delete" methods for same reason as previous.
* pxr/base/arch/attributes.h: Fix ARCH_CONSTRUCTOR and ARCH_DESTRUCTOR. This issue only showed up when trying to use …
> Fixes for calling into a USD library built with MSVC, from code built with clang-cl

- pxr/usd/usdUtils/sparseValueWriter.h
- pxr/usd/usdUtils/testenv/testUsdUtilsSparseValueWriter.py
- pxr/usd/usdUtils/wrapSparseValueWriter.cpp
Add a getter function to access _AttrValueWriterMap which makes it convenient to debug it's data.
> Add a getter function to access _AttrValueWriterMap

- README.md
Visual Studio is a 32 bit application, however certain components (e.g. MSBuild, compilers, etc... ) are 64-bit if available.
https://developercommunity.visualstudio.com/content/problem/517541/vs-2019-downloaded-x64-version-installed-x86.html
> Fix the typo for building USD on Windows.

- extras/CMakeLists.txt
Don't try to build hdTiny if imaging is disabled.
--no-imaging fails when building hdTiny.
> [extras] Don't build imaging extras if imaging is disabled.

- .gitattributes
Ensures that sdf and usda test inputs and baselines use LF on all platforms; otherwise testSdfParsing* and testUsdFlatten* fail on Windows.
-
> [tests] Checkout sdf and usda files with LF for cross-platform unit testing.

- pxr/usd/bin/usdedit/usdedit.py
[usdedit] Don't keep a file descriptor open for the temporary usda.
It is not needed, and prevents usdcat from writing to it in Windows.
Also ensure write permissions when removing the temporary usda,
otherwise usdedit -n will be unable to remove it on Windows.
`usdedit extras\usd\tutorials\convertingLayerFormats\Sphere.usd`
The process cannot access the file because it is being used by another process.
Error: Failed to open file extras\usd\tutorials\convertingLayerFormats\Sphere.usd, exiting.
> [usdedit] Don't keep a file descriptor open for the temporary usda.

- pxr/usdImaging/usdImaging/delegate.cpp
- pxr/usdImaging/usdImaging/delegate.h
- pxr/usdImaging/usdImaging/instanceAdapter.cpp
- pxr/usdImaging/usdImaging/pointInstancerAdapter.cpp
- pxr/usdImaging/usdImaging/primAdapter.cpp
- pxr/usdImaging/usdImaging/primAdapter.h
- pxr/usdImaging/usdImagingGL/drawModeAdapter.cpp
Provide an optional feature in the UsdImagingDelegate to display unloaded
prims with payloads as bounding boxes. Requires that the prim is of Model
kind and has an extentsHint authored, or is a UsdGeomBoundable and has
an extent authored.
Built on the work from Animal Logic here:
https://github.com/AnimalLogic/USD/tree/display_unloaded_prims
And taking into account Pixar's recommendations here:
https://github.com/PixarAnimationStudios/USD/pull/788
And also adding support for native and point instanced primitives.
> Allow displaying of unloaded prims as bounding boxes

- build_scripts/build_usd.py
- extras/usd/CMakeLists.txt
This makes the examples set (usdObj, etc) optional to build. This is desirable for applications embedding a USD build which want a minimal set of components.
- None filed.
> [Build] Make examples+tutorials optional.

- pxr/usd/pcp/dynamicFileFormatInterface.h
Provide a virtual destructor for PcpDynamicFileFormatInterface to prevent
build errors with some compiler/linker combinations when building plugins
containing subclasses of this class. In particular, gcc compilers with
-Werror=non-virtual-dtor would fail without this.
Add an empty virtual destructor to the abstract PcpDynamicFileFormatInterface base class.
> Provide a virtual destructor for PcpDynamicFileFormatInterface

- pxr/usd/plugin/usdMtlx/testenv/testUsdMtlxFileFormat.py
- pxr/usd/plugin/usdMtlx/testenv/testUsdMtlxFileFormat.testenv/baseline/Looks.usda
- pxr/usd/plugin/usdMtlx/testenv/testUsdMtlxFileFormat.testenv/baseline/NodeGraphs.usda
Updating this test based on conversations when we reviewed some python 3 related changes. This switches to using a layer export instead of opening a file and writing to it using ExportToString. Each baseline needed to have a new line removed from the end, but they are identical aside from that.
> [usdMtlx] Use Export in test instead of ExportToString

- pxr/usd/lib/usd/wrapStage.cpp
Test weak pointer's validity in `__repr__`.
- Crash when printing an expired stage python object
> Fix crash when printing an expired stage python object
